version: '2.1'
services:
  checkmk:
    container_name: checkmk
    image: registry.checkmk.com/enterprise/check-mk-enterprise:2.1.0p24
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024
    volumes:
      - ./monitoring:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:5000"
      - "6557:6557"
    environment:
      - CMK_SITE_ID=livvman
      - CMK_PASSWORD=Pa55p0rt
      - CMK_LIVESTATUS_TCP=on
    restart: unless-stopped
    networks:
      - traefik-hub

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok
    networks: 
      - traefik-hub
    volumes:
      - ./ngrok.yaml:/etc/ngrok.yaml
    environment:
      - NGROK_CONFIG=/etc/ngrok.yaml
    depends_on:
      - checkmk
volumes:
    data:
networks:
  traefik-hub: {}
